(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('LIST->JS-ARRAY');
var l2=internals.intern('*ROOT*');
var l3=internals.make_lisp_string('Array');
var l4=internals.make_lisp_string('push');
var l5=internals.intern('MAPC','COMMON-LISP');
l1.fvalue=(function(){var FUNC=(function JSCL_USER_LISTJSARRAY(values,v1){internals.checkArgs(arguments.length-1,1);
var v2=this;
return (function(){return (function(v4){l5.fvalue(internals.pv,(function JSCL_USER_NIL(values,v5){internals.checkArgs(arguments.length-1,1);
var v6=this;
return internals.js_to_lisp(v4[internals.xstring(l4)](internals.lisp_to_js(v5)));
}),v1);
return v4;
})(internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l3)]()));
})();
});
FUNC.fname='LIST->JS-ARRAY';
return FUNC;
})();
l1;
var l6=internals.intern('JS-OBJECT-ASSIGN');
var l7=internals.make_lisp_string('Object');
var l8=internals.make_lisp_string('assign');
l6.fvalue=(function(){var FUNC=(function JSCL_USER_JSOBJECTASSIGN(values,v7,v8){internals.checkArgs(arguments.length-1,2);
var v9=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l7)][internals.xstring(l8)](internals.lisp_to_js(v7),internals.lisp_to_js(v8)));
})();
});
FUNC.fname='JS-OBJECT-ASSIGN';
return FUNC;
})();
l6;
var l9=internals.intern('MAKE-JS-ARRAY');
var l10=internals.intern('ARRAYP','COMMON-LISP');
var l11=internals.intern('NIL','COMMON-LISP');
var l12=internals.intern('LISTP','COMMON-LISP');
var l13=internals.intern('LIST','COMMON-LISP');
l9.fvalue=(function(){var FUNC=(function JSCL_USER_MAKEJSARRAY(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return (function(){return l10.fvalue(internals.pv,v11)!==l11.value?v11:l12.fvalue(internals.pv,v11)!==l11.value?l1.fvalue(values,v11):l1.fvalue(values,l13.fvalue(internals.pv,v11));
})();
});
FUNC.fname='MAKE-JS-ARRAY';
return FUNC;
})();
l9;
var l14=internals.intern('FLAT-LIST');
var l15=internals.intern('NULL','COMMON-LISP');
var l16=internals.intern('REVERSE','COMMON-LISP');
l14.fvalue=(function(){var FUNC=(function JSCL_USER_FLATLIST(values,v14){internals.checkArgs(arguments.length-1,1);
var v15=this;
return (function(){return (function(v17){return (function(){var v18=(function JSCL_USER_NIL(values,v19){internals.checkArgs(arguments.length-1,1);
var v20=this;
return (function(){return (function(v22){return v22!==l11.value?v22:l12.fvalue(internals.pv,v19)!==l11.value?(v18(internals.pv,internals.car(v19)),v18(values,internals.cdr(v19))):(function(){var v24=v19;
var v25=new internals.Cons(v24,v17);
return v17=v25;
})();
})(l15.fvalue(internals.pv,v19));
})();
});
v18(internals.pv,v14);
return l16.fvalue(values,v17);
})();
})(l11.value);
})();
});
FUNC.fname='FLAT-LIST';
return FUNC;
})();
l14;
var l17=internals.intern('HASH-TABLE->JS-OBJECT');
var l18=internals.intern('MAPHASH','COMMON-LISP');
l17.fvalue=(function(){var FUNC=(function JSCL_USER_HASHTABLEJSOBJECT(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
return (function(){return (function(v29){l18.fvalue(internals.pv,(function JSCL_USER_NIL(values,v30,v31){internals.checkArgs(arguments.length-1,2);
var v32=this;
return (function(){var v34=v29;
var v35=v30;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v37){switch(arguments.length-1){case 0:v37=l11.value;
;
default:break;
}var v36=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v36=new internals.Cons(arguments[I+1],v36);
var v38=this;
return (function(){var OBJ=v34;
var TMP=OBJ[internals.xstring(v35)]=internals.lisp_to_js(v37);
return TMP===undefined?l11.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v31;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}),v26);
return v29;
})({});
})();
});
FUNC.fname='HASH-TABLE->JS-OBJECT';
return FUNC;
})();
l17;
var l19=internals.intern('JS-OBJECT->HASH-TABLE');
var l20=internals.intern('TEST','KEYWORD');
l20.value=l20;
var l21=internals.intern('EQUAL','COMMON-LISP');
var l22=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
var l23=internals.make_lisp_string('Object');
var l24=internals.make_lisp_string('keys');
var l25=internals.intern('LENGTH','COMMON-LISP');
var l26=internals.intern('T','COMMON-LISP');
var l27=internals.intern('AREF','COMMON-LISP');
var l28=internals.intern('1+','COMMON-LISP');
var l29=internals.intern('STRING','COMMON-LISP');
var l30=internals.intern('SETHASH');
l19.fvalue=(function(){var FUNC=(function JSCL_USER_JSOBJECTHASHTABLE(values,v39){internals.checkArgs(arguments.length-1,1);
var v40=this;
return (function(){return (function(v42){(function(v43,v44,v45,v46){return (function(v47){return (function(){var v49=l13.fvalue(internals.pv,l11.value);
var v50=v49;
return (function(){try{var v51=[];
return (function(){var v52=1;
var v53=[];
TBLOOP:while (true){try{switch(v52){case 1:v46=l25.fvalue(internals.pv,v44);
case 2:if ((function(){var x1=v45;
if (typeof x1!='number') throw 'Not a number!';
var x2=v46;
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l26.value:l11.value;
})()!==l11.value) (function(){throw new internals.TagNLX(v53,3);
})();
 else l11.value;
v43=l27.fvalue(internals.pv,v44,v45);
v45=l28.fvalue(internals.pv,v45);
v47=l29.fvalue(internals.pv,v43);
(function(){var TMP=v50;
TMP.cdr=v50=l13.fvalue(internals.pv,(function(){var v55=v47;
var v56=v42;
var v57=l11.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v59){switch(arguments.length-1){case 0:v59=l11.value;
;
default:break;
}var v58=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v58=new internals.Cons(arguments[I+1],v58);
var v60=this;
return l30.fvalue(internals.pv,v59,v55,v56),v59;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.js_to_lisp((function(){var TMP=v39[internals.xstring(v47)];
return TMP===undefined?l11.value:TMP;
})());
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})());
return TMP;
})();
(function(){throw new internals.TagNLX(v53,2);
})();
case 3:(function(){throw new internals.BlockNLX(v51,internals.cdr(v49),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v53) v52=JUMP.label;
 else throw JUMP;
}}return l11.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v51) return CF.values;
 else throw CF;
}})();
})();
})(l11.value);
})(l11.value,internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l23)][internals.xstring(l24)](internals.lisp_to_js(v39))),0,0);
return v42;
})(l22.fvalue(internals.pv,l20.value,internals.symbolFunction(l21)));
})();
});
FUNC.fname='JS-OBJECT->HASH-TABLE';
return FUNC;
})();
l19;
var l31=internals.intern('HASH-TABLE->LIST');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_HASHTABLELIST(values,v61){internals.checkArgs(arguments.length-1,1);
var v62=this;
return (function(){return (function(v64){l18.fvalue(internals.pv,(function JSCL_USER_NIL(values,v65,v66){internals.checkArgs(arguments.length-1,2);
var v67=this;
return (function(){var v69=new internals.Cons(v65,v66);
var v70=new internals.Cons(v69,v64);
return v64=v70;
})();
}),v61);
return v64;
})(l11.value);
})();
});
FUNC.fname='HASH-TABLE->LIST';
return FUNC;
})();
l31;
var l32=internals.intern('LIST->HASH-TABLE');
var l33=internals.intern('MAPCAR','COMMON-LISP');
l32.fvalue=(function(){var FUNC=(function JSCL_USER_LISTHASHTABLE(values,v71){internals.checkArgs(arguments.length-1,1);
var v72=this;
return (function(){return (function(v74){l33.fvalue(internals.pv,(function JSCL_USER_NIL(values,v75){internals.checkArgs(arguments.length-1,1);
var v76=this;
return (function(){var v78=internals.car(v75);
var v79=v74;
var v80=l11.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v82){switch(arguments.length-1){case 0:v82=l11.value;
;
default:break;
}var v81=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v81=new internals.Cons(arguments[I+1],v81);
var v83=this;
return l30.fvalue(internals.pv,v82,v78,v79),v82;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=internals.cdr(v75);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}),v71);
return v74;
})(l22.fvalue(internals.pv,l20.value,internals.symbolFunction(l21)));
})();
});
FUNC.fname='LIST->HASH-TABLE';
return FUNC;
})();
l32;
var l34=internals.intern('LIST->JS-OBJECT');
l34.fvalue=(function(){var FUNC=(function JSCL_USER_LISTJSOBJECT(values,v84){internals.checkArgs(arguments.length-1,1);
var v85=this;
return (function(){return l17.fvalue(values,l32.fvalue(internals.pv,v84));
})();
});
FUNC.fname='LIST->JS-OBJECT';
return FUNC;
})();
l34;
var l35=internals.intern('JS-OBJECT');
var l36=internals.intern('HASH-TABLE-P','COMMON-LISP');
l35.fvalue=(function(){var FUNC=(function JSCL_USER_JSOBJECT(values,v87){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v87=l11.value;
;
default:break;
}var v88=this;
return (function(){return l12.fvalue(internals.pv,v87)!==l11.value?l34.fvalue(values,v87):l36.fvalue(internals.pv,v87)!==l11.value?l17.fvalue(values,v87):v87;
})();
});
FUNC.fname='JS-OBJECT';
return FUNC;
})();
l35;
var l37=internals.intern('ARRAY-OR-ONE');
l37.fvalue=(function(){var FUNC=(function JSCL_USER_ARRAYORONE(values,v90){internals.checkArgs(arguments.length-1,1);
var v91=this;
return (function(){return l10.fvalue(internals.pv,v90)!==l11.value?v90:l12.fvalue(internals.pv,v90)!==l11.value?l9.fvalue(values,v90):v90;
})();
});
FUNC.fname='ARRAY-OR-ONE';
return FUNC;
})();
l37;
var l38=internals.intern('JS-MAP');
var l39=internals.make_lisp_string('Object');
var l40=internals.make_lisp_string('keys');
var l41=internals.make_lisp_string('keys: ~a');
var l42=internals.intern('FORMAT','COMMON-LISP');
l38.fvalue=(function(){var FUNC=(function JSCL_USER_JSMAP(values,v93,v94){internals.checkArgs(arguments.length-1,2);
var v95=this;
return (function(){if (l12.fvalue(internals.pv,v94)!==l11.value) (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v99){switch(arguments.length-1){case 0:v99=l11.value;
;
default:break;
}var v98=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v98=new internals.Cons(arguments[I+1],v98);
var v100=this;
return v94=v99;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l1.fvalue(values,v94);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l11.value;
return (function(v101){l42.fvalue(internals.pv,l26.value,l41,v101);
return (function(v102,v103,v104,v105){return (function(v106){return (function(){var v108=l13.fvalue(internals.pv,l11.value);
var v109=v108;
return (function(){try{var v110=[];
return (function(){var v111=1;
var v112=[];
TBLOOP:while (true){try{switch(v111){case 1:v105=l25.fvalue(internals.pv,v103);
case 2:if ((function(){var x1=v104;
if (typeof x1!='number') throw 'Not a number!';
var x2=v105;
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l26.value:l11.value;
})()!==l11.value) (function(){throw new internals.TagNLX(v112,3);
})();
 else l11.value;
v102=l27.fvalue(internals.pv,v103,v104);
v104=l28.fvalue(internals.pv,v104);
v106=l29.fvalue(internals.pv,v102);
(function(){var TMP=v109;
TMP.cdr=v109=l13.fvalue(internals.pv,(function(){var F=v93;
return (typeof F==='function'?F:F.fvalue)(internals.pv,internals.js_to_lisp((function(){var TMP=v94[internals.xstring(v106)];
return TMP===undefined?l11.value:TMP;
})()),v106);
})());
return TMP;
})();
(function(){throw new internals.TagNLX(v112,2);
})();
case 3:(function(){var values=internals.mv;
throw new internals.BlockNLX(v110,internals.cdr(v108),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v112) v111=JUMP.label;
 else throw JUMP;
}}return l11.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v110) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
})(l11.value);
})(l11.value,v101,0,0);
})(internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l39)][internals.xstring(l40)](internals.lisp_to_js(v94))));
})();
});
FUNC.fname='JS-MAP';
return FUNC;
})();
l38;
var l43=internals.intern('JS-KEY-MAP');
var l44=internals.make_lisp_string('Object');
var l45=internals.make_lisp_string('keys');
l43.fvalue=(function(){var FUNC=(function JSCL_USER_JSKEYMAP(values,v113,v114){internals.checkArgs(arguments.length-1,2);
var v115=this;
return (function(){if (l12.fvalue(internals.pv,v114)!==l11.value) (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v119){switch(arguments.length-1){case 0:v119=l11.value;
;
default:break;
}var v118=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v118=new internals.Cons(arguments[I+1],v118);
var v120=this;
return v114=v119;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l1.fvalue(values,v114);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l11.value;
return (function(v121){return (function(v122,v123,v124,v125){return (function(v126){return (function(){var v128=l13.fvalue(internals.pv,l11.value);
var v129=v128;
return (function(){try{var v130=[];
return (function(){var v131=1;
var v132=[];
TBLOOP:while (true){try{switch(v131){case 1:v125=l25.fvalue(internals.pv,v123);
case 2:if ((function(){var x1=v124;
if (typeof x1!='number') throw 'Not a number!';
var x2=v125;
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l26.value:l11.value;
})()!==l11.value) (function(){throw new internals.TagNLX(v132,3);
})();
 else l11.value;
v122=l27.fvalue(internals.pv,v123,v124);
v124=l28.fvalue(internals.pv,v124);
v126=l29.fvalue(internals.pv,v122);
(function(){var TMP=v129;
TMP.cdr=v129=l13.fvalue(internals.pv,(function(){var F=v113;
return (typeof F==='function'?F:F.fvalue)(internals.pv,v126);
})());
return TMP;
})();
(function(){throw new internals.TagNLX(v132,2);
})();
case 3:(function(){var values=internals.mv;
throw new internals.BlockNLX(v130,internals.cdr(v128),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v132) v131=JUMP.label;
 else throw JUMP;
}}return l11.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v130) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
})(l11.value);
})(l11.value,v121,0,0);
})(internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l44)][internals.xstring(l45)](internals.lisp_to_js(v114))));
})();
});
FUNC.fname='JS-KEY-MAP';
return FUNC;
})();
l43;
var l46=internals.intern('JS-VALUE-MAP');
var l47=internals.make_lisp_string('Object');
var l48=internals.make_lisp_string('keys');
l46.fvalue=(function(){var FUNC=(function JSCL_USER_JSVALUEMAP(values,v133,v134){internals.checkArgs(arguments.length-1,2);
var v135=this;
return (function(){if (l12.fvalue(internals.pv,v134)!==l11.value) (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v139){switch(arguments.length-1){case 0:v139=l11.value;
;
default:break;
}var v138=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v138=new internals.Cons(arguments[I+1],v138);
var v140=this;
return v134=v139;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l1.fvalue(values,v134);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l11.value;
return (function(v141){return (function(v142,v143,v144,v145){return (function(v146){return (function(v147){return (function(){var v149=l13.fvalue(internals.pv,l11.value);
var v150=v149;
return (function(){try{var v151=[];
return (function(){var v152=1;
var v153=[];
TBLOOP:while (true){try{switch(v152){case 1:v145=l25.fvalue(internals.pv,v143);
case 2:if ((function(){var x1=v144;
if (typeof x1!='number') throw 'Not a number!';
var x2=v145;
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l26.value:l11.value;
})()!==l11.value) (function(){throw new internals.TagNLX(v153,3);
})();
 else l11.value;
v142=l27.fvalue(internals.pv,v143,v144);
v144=l28.fvalue(internals.pv,v144);
v146=l29.fvalue(internals.pv,v142);
v147=internals.js_to_lisp((function(){var TMP=v134[internals.xstring(v146)];
return TMP===undefined?l11.value:TMP;
})());
(function(){var TMP=v150;
TMP.cdr=v150=l13.fvalue(internals.pv,(function(){var F=v133;
return (typeof F==='function'?F:F.fvalue)(internals.pv,v147);
})());
return TMP;
})();
(function(){throw new internals.TagNLX(v153,2);
})();
case 3:(function(){var values=internals.mv;
throw new internals.BlockNLX(v151,internals.cdr(v149),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v153) v152=JUMP.label;
 else throw JUMP;
}}return l11.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v151) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
})(l11.value);
})(l11.value);
})(l11.value,v141,0,0);
})(internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l47)][internals.xstring(l48)](internals.lisp_to_js(v134))));
})();
});
FUNC.fname='JS-VALUE-MAP';
return FUNC;
})();
l46;
var l49=internals.intern('VALID-STRING');
var l50=internals.make_lisp_string('~a');
var l51=internals.intern('ASET');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_VALIDSTRING(values,v154){internals.checkArgs(arguments.length-1,1);
var v155=this;
return (function(){return (function(v157){(function(){return (function(v159,v160){(function(){while ((function(){var x1=v159;
if (typeof x1!='number') throw 'Not a number!';
var x2=v160;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l26.value:l11.value;
})()!==l11.value){(function(){var v162=v157;
var v163=v159;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v165){switch(arguments.length-1){case 0:v165=l11.value;
;
default:break;
}var v164=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v164=new internals.Cons(arguments[I+1],v164);
var v166=this;
return l51.fvalue(values,v162,v163,v165);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.safe_char_downcase(l27.fvalue(internals.pv,v157,v159));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
if ((' '===l27.fvalue(internals.pv,v157,v159)?l26.value:l11.value)!==l11.value) (function(){var v168=v157;
var v169=v159;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v171){switch(arguments.length-1){case 0:v171=l11.value;
;
default:break;
}var v170=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v170=new internals.Cons(arguments[I+1],v170);
var v172=this;
return l51.fvalue(values,v168,v169,v171);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS='_';
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l11.value;
l11.value;
(function(){var v174=1;
var v175=(function(){var x1=v159;
if (typeof x1!='number') throw 'Not a number!';
var x2=v174;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v159=v175;
})();
}return l11.value;
})();
return l11.value;
})(0,l25.fvalue(internals.pv,v157));
})();
return v157;
})(l42.fvalue(internals.pv,l11.value,l50,v154));
})();
});
FUNC.fname='VALID-STRING';
return FUNC;
})();
l49;
var l52=internals.intern('GET-ELEMENT-BY-ID');
var l53=internals.make_lisp_string('document');
var l54=internals.make_lisp_string('getElementById');
l52.fvalue=(function(){var FUNC=(function JSCL_USER_GETELEMENTBYID(values,v176){internals.checkArgs(arguments.length-1,1);
var v177=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l53)][internals.xstring(l54)](internals.lisp_to_js(v176)));
})();
});
FUNC.fname='GET-ELEMENT-BY-ID';
return FUNC;
})();
l52;
var l55=internals.intern('REACT-CREATE-ELEMENT');
var l56=internals.make_lisp_string('React');
var l57=internals.make_lisp_string('createElement');
var l58=internals.intern('BECOME-JS-OBJECT');
l55.fvalue=(function(){var FUNC=(function JSCL_USER_REACTCREATEELEMENT(values,v180,v181){internals.checkArgsAtLeast(arguments.length-1,2);
var v179=l11.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v179=new internals.Cons(arguments[I+1],v179);
var v182=this;
return (function(){return (function(){var F=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l2)[internals.xstring(l56)];
if (TMP===undefined) return l11.value;
TMP=TMP[internals.xstring(l57)];
return TMP===undefined?l11.value:TMP;
})());
var ARGS=[values,v180,l58.fvalue(internals.pv,v181)];
var TAIL=l33.fvalue(internals.pv,internals.symbolFunction(l37),v179);
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='REACT-CREATE-ELEMENT';
return FUNC;
})();
l55;
l58.fvalue=(function(){var FUNC=(function JSCL_USER_BECOMEJSOBJECT(values,v184){internals.checkArgs(arguments.length-1,1);
var v185=this;
return (function(){return l36.fvalue(internals.pv,v184)!==l11.value?l17.fvalue(values,v184):l12.fvalue(internals.pv,v184)!==l11.value?l17.fvalue(values,l32.fvalue(internals.pv,v184)):v184;
})();
});
FUNC.fname='BECOME-JS-OBJECT';
return FUNC;
})();
l58;
var l59=internals.intern('BECOME-HASH-TABLE');
l59.fvalue=(function(){var FUNC=(function JSCL_USER_BECOMEHASHTABLE(values,v187){internals.checkArgs(arguments.length-1,1);
var v188=this;
return (function(){return l19.fvalue(values,l58.fvalue(internals.pv,v187));
})();
});
FUNC.fname='BECOME-HASH-TABLE';
return FUNC;
})();
l59;
var l60=internals.intern('UL');
var l61=internals.make_lisp_string('ul');
l60.fvalue=(function(){var FUNC=(function JSCL_USER_UL(values,v191){internals.checkArgsAtLeast(arguments.length-1,1);
var v190=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v190=new internals.Cons(arguments[I+1],v190);
var v192=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l61,v191];
var TAIL=v190;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='UL';
return FUNC;
})();
l60;
var l62=internals.intern('LI');
var l63=internals.make_lisp_string('li');
l62.fvalue=(function(){var FUNC=(function JSCL_USER_LI(values,v195){internals.checkArgsAtLeast(arguments.length-1,1);
var v194=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v194=new internals.Cons(arguments[I+1],v194);
var v196=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l63,v195];
var TAIL=v194;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='LI';
return FUNC;
})();
l62;
var l64=internals.intern('DIV');
var l65=internals.make_lisp_string('div');
l64.fvalue=(function(){var FUNC=(function JSCL_USER_DIV(values,v199){internals.checkArgsAtLeast(arguments.length-1,1);
var v198=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v198=new internals.Cons(arguments[I+1],v198);
var v200=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l65,v199];
var TAIL=v198;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='DIV';
return FUNC;
})();
l64;
var l66=internals.intern('SECTION');
var l67=internals.make_lisp_string('section');
l66.fvalue=(function(){var FUNC=(function JSCL_USER_SECTION(values,v203){internals.checkArgsAtLeast(arguments.length-1,1);
var v202=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v202=new internals.Cons(arguments[I+1],v202);
var v204=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l67,v203];
var TAIL=v202;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='SECTION';
return FUNC;
})();
l66;
var l68=internals.intern('H1');
var l69=internals.make_lisp_string('h1');
l68.fvalue=(function(){var FUNC=(function JSCL_USER_H(values,v207){internals.checkArgsAtLeast(arguments.length-1,1);
var v206=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v206=new internals.Cons(arguments[I+1],v206);
var v208=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l69,v207];
var TAIL=v206;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='H1';
return FUNC;
})();
l68;
var l70=internals.intern('H2');
var l71=internals.make_lisp_string('h2');
l70.fvalue=(function(){var FUNC=(function JSCL_USER_H(values,v211){internals.checkArgsAtLeast(arguments.length-1,1);
var v210=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v210=new internals.Cons(arguments[I+1],v210);
var v212=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l71,v211];
var TAIL=v210;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='H2';
return FUNC;
})();
l70;
var l72=internals.intern('P');
var l73=internals.make_lisp_string('p');
l72.fvalue=(function(){var FUNC=(function JSCL_USER_P(values,v215){internals.checkArgsAtLeast(arguments.length-1,1);
var v214=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v214=new internals.Cons(arguments[I+1],v214);
var v216=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l73,v215];
var TAIL=v214;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='P';
return FUNC;
})();
l72;
var l74=internals.intern('ARTICLE');
var l75=internals.make_lisp_string('article');
l74.fvalue=(function(){var FUNC=(function JSCL_USER_ARTICLE(values,v219){internals.checkArgsAtLeast(arguments.length-1,1);
var v218=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v218=new internals.Cons(arguments[I+1],v218);
var v220=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l75,v219];
var TAIL=v218;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='ARTICLE';
return FUNC;
})();
l74;
var l76=internals.intern('HEADER');
var l77=internals.make_lisp_string('header');
l76.fvalue=(function(){var FUNC=(function JSCL_USER_HEADER(values,v223){internals.checkArgsAtLeast(arguments.length-1,1);
var v222=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v222=new internals.Cons(arguments[I+1],v222);
var v224=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,l77,v223];
var TAIL=v222;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='HEADER';
return FUNC;
})();
l76;
var l78=internals.intern('REACT-DOM-RENDER');
var l79=internals.make_lisp_string('ReactDOM');
var l80=internals.make_lisp_string('render');
l78.fvalue=(function(){var FUNC=(function JSCL_USER_REACTDOMRENDER(values,v226,v227){internals.checkArgs(arguments.length-1,2);
var v228=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l2)[internals.xstring(l79)][internals.xstring(l80)](internals.lisp_to_js(l37.fvalue(internals.pv,v226)),internals.lisp_to_js(v227)));
})();
});
FUNC.fname='REACT-DOM-RENDER';
return FUNC;
})();
l78;
var l81=internals.intern('INGREDIENTS-LIST');
var l82=internals.intern('ENDP','COMMON-LISP');
var l83=internals.make_lisp_string('key');
l81.fvalue=(function(){var FUNC=(function JSCL_USER_INGREDIENTSLIST(values,v230){internals.checkArgs(arguments.length-1,1);
var v231=this;
return (function(){return (function(v233){return (function(v234,v235){return (function(){var v237=l13.fvalue(internals.pv,l11.value);
var v238=v237;
return (function(){try{var v239=[];
return (function(){var v240=1;
var v241=[];
TBLOOP:while (true){try{switch(v240){case 1:if (l82.fvalue(internals.pv,v235)!==l11.value) (function(){throw new internals.TagNLX(v241,2);
})();
 else l11.value;
v234=internals.car(v235);
v235=internals.cdr(v235);
(function(){var TMP=v238;
TMP.cdr=v238=l13.fvalue(internals.pv,l62.fvalue(internals.pv,l13.fvalue(internals.pv,new internals.Cons(l83,v233)),v234));
return TMP;
})();
v233=l28.fvalue(internals.pv,v233);
(function(){throw new internals.TagNLX(v241,1);
})();
case 2:(function(){var values=internals.mv;
throw new internals.BlockNLX(v239,internals.cdr(v237),'NIL');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v241) v240=JUMP.label;
 else throw JUMP;
}}return l11.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v239) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
})(l11.value,v230);
})(0);
})();
});
FUNC.fname='INGREDIENTS-LIST';
return FUNC;
})();
l81;
var l84=internals.QIList(internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('backend-salmon')),l11);
var l85=internals.make_lisp_string('Baked Salmon');
var l86=internals.QIList(internals.QIList(internals.make_lisp_string('className'),internals.make_lisp_string('ingredients')),l11);
var l87=internals.make_lisp_string('2 lb salmon');
var l88=internals.make_lisp_string('5 sprigs fresh rosemary');
var l89=internals.make_lisp_string('2 tablespoons olive oil');
var l90=internals.make_lisp_string('2 small lemons');
var l91=internals.make_lisp_string('1 teaspoon kosher salt');
var l92=internals.make_lisp_string('4 cloves of chopped garlic');
var l93=internals.QIList(internals.QIList(internals.make_lisp_string('className'),internals.make_lisp_string('instructions')),l11);
var l94=internals.make_lisp_string('Cooking Instructions');
var l95=internals.make_lisp_string('Preheat the oven to 375 degrees.');
var l96=internals.make_lisp_string('Lightly coat aluminum foil with oil.');
var l97=internals.make_lisp_string('Place salmon on foil.');
var l98=internals.make_lisp_string('Cover with rosemary, sliced lemons, chopped garlic.');
var l99=internals.make_lisp_string('Bake for 15-20 minutes until cooked through.');
var l100=internals.make_lisp_string('Remove from oven.');
var l101=internals.make_lisp_string('root');
l78.fvalue(internals.pv,l66.fvalue(internals.pv,l84,l68.fvalue(internals.pv,l11.value,l85),l60.fvalue(internals.pv,l86,l81.fvalue(internals.pv,l13.fvalue(internals.pv,l87,l88,l89,l90,l91,l92))),l66.fvalue(internals.pv,l93,l70.fvalue(internals.pv,l11.value,l94),l72.fvalue(internals.pv,l11.value,l95),l72.fvalue(internals.pv,l11.value,l96),l72.fvalue(internals.pv,l11.value,l97),l72.fvalue(internals.pv,l11.value,l98),l72.fvalue(internals.pv,l11.value,l99),l72.fvalue(internals.pv,l11.value,l100))),l52.fvalue(internals.pv,l101));
var l102=internals.intern('DATA');
var l103=internals.make_lisp_string('name');
var l104=internals.make_lisp_string('Baked Salmon');
var l105=internals.make_lisp_string('ingredients');
var l106=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Salmon')),internals.QIList(internals.make_lisp_string('amount'),1),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('l lb')),l11);
var l107=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Pine Nuts')),internals.QIList(internals.make_lisp_string('amount'),1),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cup')),l11);
var l108=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Butter Lettuce')),internals.QIList(internals.make_lisp_string('amount'),2),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cups')),l11);
var l109=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Yellow Squash')),internals.QIList(internals.make_lisp_string('amount'),1),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('med')),l11);
var l110=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Olive Oil')),internals.QIList(internals.make_lisp_string('amount'),0.5),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cup')),l11);
var l111=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Garlic')),internals.QIList(internals.make_lisp_string('amount'),3),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cloves')),l11);
var l112=internals.make_lisp_string('steps');
var l113=internals.QIList(internals.make_lisp_string('Preheat the oven to 350 degrees.'),internals.make_lisp_string('Spread the olive oil around a glass baking dish.'),internals.make_lisp_string('Add the salmon, garlic, and pine nuts to the dish.'),internals.make_lisp_string('Bake for 15 minutes.'),internals.make_lisp_string('Add the yellow squash and put back in the oven for 30 mins.'),internals.make_lisp_string('Remove from oven and let cool for 15 minutes. Add the lettuce and serve.'),l11);
var l114=internals.make_lisp_string('name');
var l115=internals.make_lisp_string('Fish Tacos');
var l116=internals.make_lisp_string('ingredients');
var l117=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Whitefish')),internals.QIList(internals.make_lisp_string('amount'),1),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('l lb')),l11);
var l118=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Cheese')),internals.QIList(internals.make_lisp_string('amount'),1),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cup')),l11);
var l119=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Iceberg Lettuce')),internals.QIList(internals.make_lisp_string('amount'),2),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('cups')),l11);
var l120=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Tomatoes')),internals.QIList(internals.make_lisp_string('amount'),2),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('large')),l11);
var l121=internals.QIList(internals.QIList(internals.make_lisp_string('name'),internals.make_lisp_string('Tortillas')),internals.QIList(internals.make_lisp_string('amount'),3),internals.QIList(internals.make_lisp_string('measurement'),internals.make_lisp_string('med')),l11);
var l122=internals.make_lisp_string('steps');
var l123=internals.QIList(internals.make_lisp_string('Cook the fish on the grill until hot.'),internals.make_lisp_string('Place the fish on the 3 tortillas.'),internals.make_lisp_string('Top them with lettuce, tomatoes, and cheese'),l11);
l102.fvalue=(function(){var FUNC=(function JSCL_USER_DATA(values){internals.checkArgsAtMost(arguments.length-1,0);
var v242=this;
return (function(){return l13.fvalue(values,l35.fvalue(internals.pv,l13.fvalue(internals.pv,new internals.Cons(l103,l104),new internals.Cons(l105,l13.fvalue(internals.pv,l35.fvalue(internals.pv,l106),l35.fvalue(internals.pv,l107),l35.fvalue(internals.pv,l108),l35.fvalue(internals.pv,l109),l35.fvalue(internals.pv,l110),l35.fvalue(internals.pv,l111))),new internals.Cons(l112,l113))),l35.fvalue(internals.pv,l13.fvalue(internals.pv,new internals.Cons(l114,l115),new internals.Cons(l116,l13.fvalue(internals.pv,l35.fvalue(internals.pv,l117),l35.fvalue(internals.pv,l118),l35.fvalue(internals.pv,l119),l35.fvalue(internals.pv,l120),l35.fvalue(internals.pv,l121))),new internals.Cons(l122,l123))));
})();
});
FUNC.fname='DATA';
return FUNC;
})();
l102;
var l124=new internals.Symbol('G1039');
var l125=internals.make_lisp_string('title');
var l126=internals.make_lisp_string('recipes');
var l127=internals.make_lisp_string('title is ~a');
var l128=internals.make_lisp_string('recipes is ~a');
var l129=internals.QIList(internals.QIList(internals.make_lisp_string('className'),internals.make_lisp_string('recipes')),l11);
var l130=internals.make_lisp_string('key');
var l131=internals.intern('APPEND','COMMON-LISP');
var l132=internals.intern('RECIPE');
var l133=internals.intern('MENU');
var l134=internals.make_lisp_string('Menu');
var l135=internals.intern('OTHER');
l124.fvalue=(function(){var FUNC=(function JSCL_USER_G(values,v245){internals.checkArgsAtLeast(arguments.length-1,1);
var v244=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v244=new internals.Cons(arguments[I+1],v244);
var v246=this;
return (function(){return (function(v248,v249){l42.fvalue(internals.pv,l26.value,l127,v248);
l42.fvalue(internals.pv,l26.value,l128,v249);
return l74.fvalue(values,l11.value,l76.fvalue(internals.pv,l11.value,l68.fvalue(internals.pv,l11.value,v248)),l64.fvalue(internals.pv,l129,l38.fvalue(internals.pv,(function JSCL_USER_NIL(values,v250,v251){internals.checkArgs(arguments.length-1,2);
var v252=this;
return l132.fvalue(values,l131.fvalue(internals.pv,l13.fvalue(internals.pv,new internals.Cons(l130,v251)),l38.fvalue(internals.pv,(function JSCL_USER_NIL(values,v253,v254){internals.checkArgs(arguments.length-1,2);
var v255=this;
return new internals.Cons(v254,v253);
}),v250)));
}),v249)));
})(internals.js_to_lisp((function(){var TMP=v245[internals.xstring(l125)];
return TMP===undefined?l11.value:TMP;
})()),internals.js_to_lisp((function(){var TMP=v245[internals.xstring(l126)];
return TMP===undefined?l11.value:TMP;
})()));
})();
});
FUNC.fname='G1039';
return FUNC;
})();
l124;
l133.fvalue=(function(){var FUNC=(function JSCL_USER_MENU(values,v257){internals.checkArgsAtLeast(arguments.length-1,1);
var v256=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v256=new internals.Cons(arguments[I+1],v256);
var v258=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,internals.symbolFunction(l124),v257];
var TAIL=v256;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='MENU';
return FUNC;
})();
l133;
(function(){var v261=internals.symbolValue(l2);
var v262=l134;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v264){switch(arguments.length-1){case 0:v264=l11.value;
;
default:break;
}var v263=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v263=new internals.Cons(arguments[I+1],v263);
var v265=this;
return (function(){var OBJ=v261;
var TMP=OBJ[internals.xstring(v262)]=internals.lisp_to_js(v264);
return TMP===undefined?l11.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=(function JSCL_USER_NIL(values,v267){internals.checkArgsAtLeast(arguments.length-1,1);
var v266=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v266=new internals.Cons(arguments[I+1],v266);
var v268=this;
return (function(){var F=internals.symbolFunction(l124);
var ARGS=[values,v267];
var TAIL=internals.symbolValue(l135);
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
});
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
var l136=new internals.Symbol('G1114');
var l137=internals.make_lisp_string('name');
var l138=internals.make_lisp_string('ingredients');
var l139=internals.make_lisp_string('steps');
var l140=internals.make_lisp_string('id');
var l141=internals.QIList(internals.QIList(internals.make_lisp_string('className'),internals.make_lisp_string('ingredients')),l11);
var l142=internals.make_lisp_string('key');
var l143=internals.make_lisp_string('name');
var l144=internals.QIList(internals.QIList(internals.make_lisp_string('className'),internals.make_lisp_string('instructions')),l11);
var l145=internals.make_lisp_string('Cooking Instructions');
var l146=internals.make_lisp_string('key');
var l147=internals.make_lisp_string('Recipe');
l136.fvalue=(function(){var FUNC=(function JSCL_USER_G(values,v270){internals.checkArgsAtLeast(arguments.length-1,1);
var v269=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v269=new internals.Cons(arguments[I+1],v269);
var v271=this;
return (function(){return (function(v273,v274,v275){return l66.fvalue(values,l13.fvalue(internals.pv,new internals.Cons(l140,l49.fvalue(internals.pv,v273))),l68.fvalue(internals.pv,l11.value,v273),l60.fvalue(internals.pv,l141,l38.fvalue(internals.pv,(function JSCL_USER_NIL(values,v276,v277){internals.checkArgs(arguments.length-1,2);
var v278=this;
return l62.fvalue(values,l13.fvalue(internals.pv,new internals.Cons(l142,v277)),internals.js_to_lisp((function(){var TMP=v276[internals.xstring(l143)];
return TMP===undefined?l11.value:TMP;
})()));
}),v274)),l66.fvalue(internals.pv,l144,l70.fvalue(internals.pv,l11.value,l145),l38.fvalue(internals.pv,(function JSCL_USER_NIL(values,v279,v280){internals.checkArgs(arguments.length-1,2);
var v281=this;
return l72.fvalue(values,l13.fvalue(internals.pv,new internals.Cons(l146,v280)),v279);
}),v275)));
})(internals.js_to_lisp((function(){var TMP=v270[internals.xstring(l137)];
return TMP===undefined?l11.value:TMP;
})()),internals.js_to_lisp((function(){var TMP=v270[internals.xstring(l138)];
return TMP===undefined?l11.value:TMP;
})()),internals.js_to_lisp((function(){var TMP=v270[internals.xstring(l139)];
return TMP===undefined?l11.value:TMP;
})()));
})();
});
FUNC.fname='G1114';
return FUNC;
})();
l136;
l132.fvalue=(function(){var FUNC=(function JSCL_USER_RECIPE(values,v283){internals.checkArgsAtLeast(arguments.length-1,1);
var v282=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v282=new internals.Cons(arguments[I+1],v282);
var v284=this;
return (function(){return (function(){var F=internals.symbolFunction(l55);
var ARGS=[values,internals.symbolFunction(l136),v283];
var TAIL=v282;
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='RECIPE';
return FUNC;
})();
l132;
(function(){var v287=internals.symbolValue(l2);
var v288=l147;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v290){switch(arguments.length-1){case 0:v290=l11.value;
;
default:break;
}var v289=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v289=new internals.Cons(arguments[I+1],v289);
var v291=this;
return (function(){var OBJ=v287;
var TMP=OBJ[internals.xstring(v288)]=internals.lisp_to_js(v290);
return TMP===undefined?l11.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=(function JSCL_USER_NIL(values,v293){internals.checkArgsAtLeast(arguments.length-1,1);
var v292=l11.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v292=new internals.Cons(arguments[I+1],v292);
var v294=this;
return (function(){var F=internals.symbolFunction(l136);
var ARGS=[values,v293];
var TAIL=internals.symbolValue(l135);
while (TAIL!=l11.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
});
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
var l148=internals.make_lisp_string('recipes');
var l149=internals.make_lisp_string('title');
var l150=internals.make_lisp_string('Delicious Recipes');
var l151=internals.make_lisp_string('root');
if (l26.value!==l11.value) {(function(v295){return l78.fvalue(internals.pv,v295,l52.fvalue(internals.pv,l151));
})(l133.fvalue(internals.pv,l13.fvalue(internals.pv,new internals.Cons(l148,l102.fvalue(internals.pv)),new internals.Cons(l149,l150))));
l11.value;
} else l11.value;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
